# Change these first
owner: youngzyl # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: home_page
    url: $MY_HOME_PAGE
  - name: BwgCA_443
    check: "tcp-ping"
    url: $MY_BWG_CA
    port: 443
  - name: CoalcloudHK_443
    check: "tcp-ping"
    url: $MY_COALCLOUD_HK
    port: 443
  - name: BwgCA
    url: $MY_BWG_CA
  - name: CloudconeCA
    url: $MY_CLOUDCONE_CA
  - name: OracleTokyo
    url: $MY_ORACLE_TOKYO
  - name: CoalcloudHK
    url: $MY_COALCLOUD_HK
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
